<a href="https://colab.research.google.com/github/kurotiyamitali-dotcom/Python-basic-project/blob/main/task15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google.colab import files

uploaded = files.upload()

Saving countries of the world.csv to countries of the world.csv

In [ ]:
df = pd.read_csv("countries of the world.csv")
print(df.head())

           Country                               Region  Population  \
0     Afghanistan         ASIA (EX. NEAR EAST)             31056997
1         Albania   EASTERN EUROPE                          3581655
2         Algeria   NORTHERN AFRICA                        32930091
3  American Samoa   OCEANIA                                   57794
4         Andorra   WESTERN EUROPE                            71201

   Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0          647500                       48,0                         0,00
1           28748                      124,6                         1,26
2         2381740                       13,8                         0,04
3             199                      290,4                        58,29
4             468                      152,1                         0,00

  Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0         23,06                             163,07               700.0
1         -4,93                              21,52              4500.0
2         -0,39                                 31              6000.0
3        -20,71                               9,27              8000.0
4           6,6                               4,05             19000.0

  Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0         36,0               3,2      12,13      0,22     87,65       1
1         86,5              71,2      21,09      4,42     74,49       3
2         70,0              78,1       3,22      0,25     96,53       1
3         97,0             259,5         10        15        75       2
4        100,0             497,2       2,22         0     97,78       3

  Birthrate Deathrate Agriculture Industry Service
0      46,6     20,34        0,38     0,24    0,38
1     15,11      5,22       0,232    0,188   0,579
2     17,14      4,61       0,101      0,6   0,298
3     22,46      3,27         NaN      NaN     NaN
4      8,71      6,25         NaN      NaN     NaN

In [ ]:
df.head()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN

In [ ]:
df.tail()

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
222,West Bank,NEAR EAST,2460492,5860,"419,9","0,00","2,98","19,62",800.0,NaN,"145,2","16,9","18,97","64,13",3,"31,67","3,92","0,09","0,28","0,63"
223,Western Sahara,NORTHERN AFRICA,273008,266000,"1,0","0,42",NaN,NaN,NaN,NaN,NaN,"0,02",0,"99,98",1,NaN,NaN,NaN,NaN,"0,4"
224,Yemen,NEAR EAST,21456188,527970,"40,6","0,36",0,"61,5",800.0,"50,2","37,2","2,78","0,24","96,98",1,"42,89","8,3","0,135","0,472","0,393"
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,"15,3","0,00",0,"88,29",800.0,"80,6","8,2","7,08","0,03","92,9",2,41,"19,93","0,22","0,29","0,489"
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,"31,3","0,00",0,"67,69",1900.0,"90,7","26,8","8,32","0,34","91,34",2,"28,01","21,84","0,179","0,243","0,579"

In [ ]:
df.shape

(227, 20)

In [ ]:
df.columns

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 20 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             227 non-null    object
 1   Region                              227 non-null    object
 2   Population                          227 non-null    int64
 3   Area (sq. mi.)                      227 non-null    int64
 4   Pop. Density (per sq. mi.)          227 non-null    object
 5   Coastline (coast/area ratio)        227 non-null    object
 6   Net migration                       224 non-null    object
 7   Infant mortality (per 1000 births)  224 non-null    object
 8   GDP ($ per capita)                  226 non-null    float64
 9   Literacy (%)                        209 non-null    object
 10  Phones (per 1000)                   223 non-null    object
 11  Arable (%)                          225 non-null    object
 12  Crops (%)                           225 non-null    object
 13  Other (%)                           225 non-null    object
 14  Climate                             205 non-null    object
 15  Birthrate                           224 non-null    object
 16  Deathrate                           223 non-null    object
 17  Agriculture                         212 non-null    object
 18  Industry                            211 non-null    object
 19  Service                             212 non-null    object
dtypes: float64(1), int64(2), object(17)
memory usage: 35.6+ KB

In [ ]:
df.describe()

         Population  Area (sq. mi.)  GDP ($ per capita)
count  2.270000e+02    2.270000e+02          226.000000
mean   2.874028e+07    5.982270e+05         9689.823009
std    1.178913e+08    1.790282e+06        10049.138513
min    7.026000e+03    2.000000e+00          500.000000
25%    4.376240e+05    4.647500e+03         1900.000000
50%    4.786994e+06    8.660000e+04         5550.000000
75%    1.749777e+07    4.418110e+05        15700.000000
max    1.313974e+09    1.707520e+07        55100.000000

In [ ]:
df.dtypes

Country                                object
Region                                 object
Population                              int64
Area (sq. mi.)                          int64
Pop. Density (per sq. mi.)             object
Coastline (coast/area ratio)           object
Net migration                          object
Infant mortality (per 1000 births)     object
GDP ($ per capita)                    float64
Literacy (%)                           object
Phones (per 1000)                      object
Arable (%)                             object
Crops (%)                              object
Other (%)                              object
Climate                                object
Birthrate                              object
Deathrate                              object
Agriculture                            object
Industry                               object
Service                                object
dtype: object

In [ ]:
df.isnull().sum()

Country                                0
Region                                 0
Population                             0
Area (sq. mi.)                         0
Pop. Density (per sq. mi.)             0
Coastline (coast/area ratio)           0
Net migration                          3
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Phones (per 1000)                      4
Arable (%)                             2
Crops (%)                              2
Other (%)                              2
Climate                               22
Birthrate                              3
Deathrate                              4
Agriculture                           15
Industry                              16
Service                               15
dtype: int64

In [ ]:
df.nunique

<bound method DataFrame.nunique of              Country                               Region  Population  \
0       Afghanistan         ASIA (EX. NEAR EAST)             31056997
1           Albania   EASTERN EUROPE                          3581655
2           Algeria   NORTHERN AFRICA                        32930091
3    American Samoa   OCEANIA                                   57794
4           Andorra   WESTERN EUROPE                            71201
..               ...                                  ...         ...
222       West Bank   NEAR EAST                               2460492
223  Western Sahara   NORTHERN AFRICA                          273008
224           Yemen   NEAR EAST                              21456188
225          Zambia   SUB-SAHARAN AFRICA                     11502010
226        Zimbabwe   SUB-SAHARAN AFRICA                     12236805

     Area (sq. mi.) Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
0            647500                       48,0                         0,00
1             28748                      124,6                         1,26
2           2381740                       13,8                         0,04
3               199                      290,4                        58,29
4               468                      152,1                         0,00
..              ...                        ...                          ...
222            5860                      419,9                         0,00
223          266000                        1,0                         0,42
224          527970                       40,6                         0,36
225          752614                       15,3                         0,00
226          390580                       31,3                         0,00

    Net migration Infant mortality (per 1000 births)  GDP ($ per capita)  \
0           23,06                             163,07               700.0
1           -4,93                              21,52              4500.0
2           -0,39                                 31              6000.0
3          -20,71                               9,27              8000.0
4             6,6                               4,05             19000.0
..            ...                                ...                 ...
222          2,98                              19,62               800.0
223           NaN                                NaN                 NaN
224             0                               61,5               800.0
225             0                              88,29               800.0
226             0                              67,69              1900.0

    Literacy (%) Phones (per 1000) Arable (%) Crops (%) Other (%) Climate  \
0           36,0               3,2      12,13      0,22     87,65       1
1           86,5              71,2      21,09      4,42     74,49       3
2           70,0              78,1       3,22      0,25     96,53       1
3           97,0             259,5         10        15        75       2
4          100,0             497,2       2,22         0     97,78       3
..           ...               ...        ...       ...       ...     ...
222          NaN             145,2       16,9     18,97     64,13       3
223          NaN               NaN       0,02         0     99,98       1
224         50,2              37,2       2,78      0,24     96,98       1
225         80,6               8,2       7,08      0,03      92,9       2
226         90,7              26,8       8,32      0,34     91,34       2

    Birthrate Deathrate Agriculture Industry Service
0        46,6     20,34        0,38     0,24    0,38
1       15,11      5,22       0,232    0,188   0,579
2       17,14      4,61       0,101      0,6   0,298
3       22,46      3,27         NaN      NaN     NaN
4        8,71      6,25         NaN      NaN     NaN
..        ...       ...         ...      ...     ...
222     31,67      3,92        0,09     0,28    0,63
223       NaN       NaN         NaN      NaN     0,4
224     42,89       8,3       0,135    0,472   0,393
225        41     19,93        0,22     0,29   0,489
226     28,01     21,84       0,179    0,243   0,579

[227 rows x 20 columns]>

In [ ]:
df.sample(5)

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
119,Liechtenstein,WESTERN EUROPE,33987,160,"212,4","0,00","4,85","4,7",25000.0,"100,0","585,5",25,0,75,4,"10,21","7,18","0,06","0,39","0,55"
206,Turkey,NEAR EAST,70413958,780580,"90,2","0,92",0,"41,04",6700.0,"86,5","269,5","30,93","3,31","65,76",3,"16,62","5,97","0,117","0,298","0,585"
126,Malaysia,ASIA (EX. NEAR EAST),24385858,329750,"74,0","1,42",0,"17,7",9000.0,"88,7","179,0","5,48","17,61","76,91",2,"22,86","5,05","0,084","0,48","0,436"
78,Gibraltar,WESTERN EUROPE,27928,7,"3989,7","171,43",0,"5,13",17500.0,NaN,"877,7",0,0,100,NaN,"10,74","9,31",NaN,NaN,NaN
75,Georgia,C.W. OF IND. STATES,4661473,69700,"66,9","0,44","-4,7","18,59",2500.0,"99,0","146,6","11,44","3,86","84,7",3,"10,41","9,23","0,172","0,275","0,553"

In [ ]:
df["Country"].value_counts()

Country
Afghanistan        1
Albania            1
Algeria            1
American Samoa     1
Andorra            1
                  ..
West Bank          1
Western Sahara     1
Yemen              1
Zambia             1
Zimbabwe           1
Name: count, Length: 227, dtype: int64